spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roulette
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
---
spring:
  profiles: docker-compose
  rabbitmq:
    host: rabbitmq
    port: 5672
  jpa:
    show-sql: false
  datasource:
      url: jdbc:mysql://mysql:3306/roulette
      username: root
      password: password