spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/roulette
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
---
spring:
  profiles: docker-compose
  rabbitmq:
    host: rabbitmq
    port: 5672
  jpa:
    show-sql: false